version: "3"

services:
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.swarm=true"
      - "--providers.swarm.watch=true"
      - "--providers.swarm.network=localpaas_net"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
    networks:
      # Connect to the 'localpaas_net' overlay network for inter-container communication across nodes
      - localpaas_net
    ports:
      # Expose traefik's entry points to the Swarm
      # Swarm requires the long syntax for ports.
      - target: 80 # Container port
        published: 80 # Host port exposed on the nodes
        protocol: tcp
        # 'host' mode binds directly to the node's IP where the task runs.
        # 'ingress' mode uses Swarm's Routing Mesh (load balances across nodes).
        # Choose based on your load balancing strategy. 'host' is often simpler if using an external LB.
        mode: host
      - target: 443 # Container port
        published: 443 # Host port
        protocol: tcp
        mode: host
      - target: 8080 # Traefik dashboard
        published: 38081 # Exposed dashboard
        protocol: tcp
        mode: host
    volumes:
      - ./localpaas/traefik/etc/dynamic:/etc/traefik/dynamic
      - ./localpaas/ssl/certs:/etc/traefik/ssl/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  db:
    image: postgres:18-alpine
    networks:
      - internal_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_DB: localpaas
      POSTGRES_USER: localpaas
      POSTGRES_PASSWORD: abc123
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: redis-server
    networks:
      - internal_net
    volumes:
      - redis:/data

  adminer:
    image: adminer:latest
    restart: unless-stopped
    networks:
      - localpaas_net
      - internal_net
    volumes:
      - adminer:/data
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adminer.rule=Host(`adminer.dev.localpaas.com`)"
        - "traefik.http.routers.adminer.entrypoints=websecure"
        - "traefik.http.routers.adminer.tls=true"
        - "traefik.http.routers.adminer-http.rule=Host(`adminer.dev.localpaas.com`)"
        - "traefik.http.routers.adminer-http.entrypoints=web"
        - "traefik.http.services.adminer.loadbalancer.server.port=8080"
        - "traefik.docker.network=localpaas_net"

  hello-world:
    image: crccheck/hello-world:latest
    restart: unless-stopped
    networks:
      - localpaas_net

  app:
    image: localpaas/localpaas-dev:app-latest
    networks:
      - localpaas_net
      - internal_net
    environment:
      LP_CONFIG_FILE: config/config.development.toml
      VITE_API_URL: http://localhost:10000
    volumes:
      - ./localpaas:/var/lib/localpaas
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.app-svc.loadbalancer.server.port=10000"
        - "traefik.http.routers.app-router.rule=Host(`app.dev.localpaas.com`)"
        - "traefik.http.routers.app-router.entrypoints=websecure"
        - "traefik.http.routers.app-router.tls=true"
        - "traefik.http.routers.app-router-http-acme.rule=Host(`*`) && PathPrefix(`/.well-known/acme-challenge/`)"
        - "traefik.http.routers.app-router-http-acme.entrypoints=web"
        - "traefik.http.middlewares.addprefix-le-acme.addprefix.prefix=/letenscrypt"
        - "traefik.http.routers.app-router-http-acme.middlewares=addprefix-le-acme"
        - "traefik.docker.network=localpaas_net"

networks:
  localpaas_net:
    external: true
  internal_net:
    driver: overlay
    attachable: true

volumes:
  db_data:
    driver: local
  adminer:
    driver: local
  redis:
    driver: local
  redis_ui:
    driver: local
