############################################################
# Build backend
FROM golang:1.26-alpine AS builder

RUN apk update && \
    apk add --no-cache -U tzdata make git build-base ca-certificates && \
    rm -rf /var/cache/apk/*

# ENV vars
ENV CGO_ENABLED=0

# Move to working directory /build
WORKDIR /build

# Copy the code into the container
COPY . .

# Copy and download dependency using go mod
RUN make mod

# Build the agent application
RUN go build -o localpaas-agent ./localpaas_app/cmd/agent/...

############################################################
# Build a small image
FROM alpine:3.23
WORKDIR /localpaas

RUN apk update && \
    apk add --no-cache ca-certificates make openssl postgresql-client git git-lfs openssh-client zstd lz4 docker-cli && \
    git lfs install --system && \
    rm -rf /var/cache/apk/*

# Copy compiled agent binary and base configurations
COPY --from=builder /build/localpaas-agent .
COPY --from=builder /build/config ./config

# Command to run
CMD ["./localpaas-agent"]
