version: "3"

services:
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.swarm=true"
      - "--providers.swarm.watch=true"
      - "--providers.swarm.network=localpaas_net"
      - "--providers.swarm.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--log.level=DEBUG"
      - "--log.filepath=/var/log/traefik/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
    networks:
      - localpaas_net
    ports:
      # Expose traefik's entry points to the Swarm
      # Swarm requires the long syntax for ports.
      - target: 80 # Container port
        published: 80 # Host port exposed on the nodes
        protocol: tcp
        # 'host' mode binds directly to the node's IP where the task runs.
        # 'ingress' mode uses Swarm's Routing Mesh (load balances across nodes).
        # Choose based on your load balancing strategy. 'host' is often simpler if using an external LB.
        mode: host
      - target: 443 # Container port
        published: 443 # Host port
        protocol: tcp
        mode: host
      - target: 8080 # Traefik dashboard
        published: 38081 # Exposed dashboard
        protocol: tcp
        mode: host
    volumes:
      - ./localpaas/traefik/etc:/etc/traefik
      - ./localpaas/traefik/var/log:/var/log/traefik
      - ./localpaas/ssl/certs:/etc/traefik/ssl/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  db:
    image: postgres:18-alpine
    networks:
      - local_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_DB: localpaas
      POSTGRES_USER: localpaas
      POSTGRES_PASSWORD: abc123
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - localpaas_db:/var/lib/postgresql
    deploy:
      labels:
        - "traefik.enable=false"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: redis-server
    networks:
      - local_net
    deploy:
      labels:
        - "traefik.enable=false"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  adminer:
    image: adminer:latest
    restart: unless-stopped
    networks:
      - localpaas_net
      - local_net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adminer.rule=Host(`adminer.dev.localpaas.com`)"
        - "traefik.http.routers.adminer.entrypoints=websecure"
        - "traefik.http.routers.adminer.tls=true"
        - "traefik.http.routers.adminer-http.rule=Host(`adminer.dev.localpaas.com`)"
        - "traefik.http.routers.adminer-http.entrypoints=web"
        - "traefik.http.services.adminer.loadbalancer.server.port=8080"
        - "traefik.swarm.network=localpaas_net"

  app:
    image: localpaas/localpaas-dev:latest
    networks:
      - localpaas_net
      - local_net
    environment:
      LP_CONFIG_FILE: config/config.development.toml
      LP_ADMIN_USERNAME: admin
      LP_ADMIN_EMAIL: admin@domain.name
      LP_ADMIN_PASSWORD: abc123
      VITE_API_URL: http://localhost:10000
    volumes:
      - ./localpaas:/var/lib/localpaas
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.app-svc.loadbalancer.server.port=10000"
        - "traefik.http.routers.app-router.rule=Host(`app.dev.localpaas.com`)"
        - "traefik.http.routers.app-router.entrypoints=websecure"
        - "traefik.http.routers.app-router.tls=true"
        - "traefik.http.routers.app-router.service=app-svc"
        - "traefik.http.middlewares.app-router-compress.compress=true"
        - "traefik.http.middlewares.app-router-compress.compress.defaultencoding=br"
        - "traefik.http.middlewares.app-router-compress.compress.includedcontenttypes=text/plain,text/html,text/css,text/javascript,text/xml,application/javascript,application/json,application/xml,application/xml+rss,application/manifest+json,application/vnd.api+json,image/svg+xml,font/eot,font/otf,font/ttf"
        - "traefik.http.middlewares.app-router-compress.compress.minresponsebodybytes=1024"
        - "traefik.http.routers.app-router.middlewares=app-router-compress@swarm"
        - "traefik.http.routers.x-custom-router-le-acme.rule=PathPrefix(`/.well-known/acme-challenge/`)"
        - "traefik.http.routers.x-custom-router-le-acme.entrypoints=web"
        - "traefik.http.routers.x-custom-router-le-acme.tls=false"
        - "traefik.http.middlewares.x-custom-addprefix-le.addprefix.prefix=/letsencrypt"
        - "traefik.http.routers.x-custom-router-le-acme.middlewares=x-custom-addprefix-le@swarm"
        - "traefik.swarm.network=localpaas_net"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  worker:
    image: localpaas/localpaas-dev:latest
    networks:
      - local_net
    environment:
      LP_CONFIG_FILE: config/config.development.toml
      LP_RUN_MODE: worker
      LP_ADMIN_USERNAME: admin
      LP_ADMIN_EMAIL: admin@domain.name
      LP_ADMIN_PASSWORD: abc123
    volumes:
      - ./localpaas:/var/lib/localpaas
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.enable=false"
      mode: replicated
      replicas: 0
      placement:
        constraints:
          - node.role == manager

  updater:
    image: localpaas/localpaas-dev:latest
    networks:
      - local_net
    environment:
      LP_CONFIG_FILE: config/config.development.toml
      LP_RUN_MODE: updater
    volumes:
      - ./localpaas:/var/lib/localpaas
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.enable=false"
      mode: replicated
      replicas: 0
      placement:
        constraints:
          - node.role == manager

networks:
  localpaas_net:
    external: true
  local_net:
    driver: overlay
    attachable: true

volumes:
  localpaas_db:
    driver: local
