// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.31.1
// source: container.proto

package agentproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ContainerService_ContainerExec_FullMethodName = "/agent.ContainerService/ContainerExec"
)

// ContainerServiceClient is the client API for ContainerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContainerServiceClient interface {
	// ContainerExec starts a command execution in a container and pipes stdout/stderr/stdin/resize.
	ContainerExec(ctx context.Context, opts ...grpc.CallOption) (ContainerService_ContainerExecClient, error)
}

type containerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerServiceClient(cc grpc.ClientConnInterface) ContainerServiceClient {
	return &containerServiceClient{cc}
}

func (c *containerServiceClient) ContainerExec(ctx context.Context, opts ...grpc.CallOption) (ContainerService_ContainerExecClient, error) {
	stream, err := c.cc.NewStream(ctx, &ContainerService_ServiceDesc.Streams[0], ContainerService_ContainerExec_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &containerServiceContainerExecClient{stream}
	return x, nil
}

type ContainerService_ContainerExecClient interface {
	Send(*ContainerExecReq) error
	Recv() (*ContainerExecResp, error)
	grpc.ClientStream
}

type containerServiceContainerExecClient struct {
	grpc.ClientStream
}

func (x *containerServiceContainerExecClient) Send(m *ContainerExecReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *containerServiceContainerExecClient) Recv() (*ContainerExecResp, error) {
	m := new(ContainerExecResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ContainerServiceServer is the server API for ContainerService service.
// All implementations must embed UnimplementedContainerServiceServer
// for forward compatibility
type ContainerServiceServer interface {
	// ContainerExec starts a command execution in a container and pipes stdout/stderr/stdin/resize.
	ContainerExec(ContainerService_ContainerExecServer) error
	mustEmbedUnimplementedContainerServiceServer()
}

// UnimplementedContainerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedContainerServiceServer struct {
}

func (UnimplementedContainerServiceServer) ContainerExec(ContainerService_ContainerExecServer) error {
	return status.Errorf(codes.Unimplemented, "method ContainerExec not implemented")
}
func (UnimplementedContainerServiceServer) mustEmbedUnimplementedContainerServiceServer() {}

// UnsafeContainerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerServiceServer will
// result in compilation errors.
type UnsafeContainerServiceServer interface {
	mustEmbedUnimplementedContainerServiceServer()
}

func RegisterContainerServiceServer(s grpc.ServiceRegistrar, srv ContainerServiceServer) {
	s.RegisterService(&ContainerService_ServiceDesc, srv)
}

func _ContainerService_ContainerExec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ContainerServiceServer).ContainerExec(&containerServiceContainerExecServer{stream})
}

type ContainerService_ContainerExecServer interface {
	Send(*ContainerExecResp) error
	Recv() (*ContainerExecReq, error)
	grpc.ServerStream
}

type containerServiceContainerExecServer struct {
	grpc.ServerStream
}

func (x *containerServiceContainerExecServer) Send(m *ContainerExecResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *containerServiceContainerExecServer) Recv() (*ContainerExecReq, error) {
	m := new(ContainerExecReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ContainerService_ServiceDesc is the grpc.ServiceDesc for ContainerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.ContainerService",
	HandlerType: (*ContainerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ContainerExec",
			Handler:       _ContainerService_ContainerExec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "container.proto",
}
