http:
  routers:
    app-router:
      rule: "Host(`app.localhost`)"
      service: "app-service"
      entryPoints:
        - websecure
    app-router-http:
      rule: "Host(`app.localhost`)"
      service: "app-service"
      entryPoints:
        - web

  services:
    app-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:10000"
        passHostHeader: true
