version: "3"

services:
  nginx:
    image: nginx:1.29-alpine

    networks:
      # Connect to the 'localpaas_net' overlay network for inter-container communication across nodes
      - localpaas_net

    ports:
      # Expose nginx's entry points to the Swarm
      # Swarm requires the long syntax for ports.
      - target: 80 # Container port
        published: 80 # Host port exposed on the nodes
        protocol: tcp
        # 'host' mode binds directly to the node's IP where the task runs.
        # 'ingress' mode uses Swarm's Routing Mesh (load balances across nodes).
        # Choose based on your load balancing strategy. 'host' is often simpler if using an external LB.
        mode: host
      - target: 443 # Container port
        published: 443 # Host port
        protocol: tcp
        mode: host

    volumes:
      - ./localpaas/nginx/etc:/etc/nginx
      - ./localpaas/nginx/log:/var/log/nginx
      - ./localpaas/nginx/share:/usr/share/nginx
      - ./localpaas/certs:/var/lib/localpaas/certs

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  db:
    image: postgres:18-alpine
    networks:
      - internal_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_DB: localpaas
      POSTGRES_USER: localpaas
      POSTGRES_PASSWORD: abc123
    ports:
      - target: 5432 # Container port
        published: 35432 # Host port exposed on the nodes
        protocol: tcp
        mode: host
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    command: redis-server
    networks:
      - internal_net
    ports:
      - target: 6379 # Container port
        published: 36379 # Host port exposed on the nodes
        protocol: tcp
        mode: host
    volumes:
      - redis:/data

  adminer:
    image: adminer:latest
    networks:
      - localpaas_net
      - internal_net
    ports:
      - target: 8080 # Container port
        published: 38080 # Host port exposed on the nodes
        protocol: tcp
        mode: host

  whodb:
    image: clidey/whodb:latest
    networks:
      - localpaas_net
      - internal_net
    ports:
      - target: 8080 # Container port
        published: 38081 # Host port exposed on the nodes
        protocol: tcp
        mode: host

#  redis_ui:
#    image: redislabs/redisinsight:latest
#    networks:
#      - internal_net
#    ports:
#      - target: 8001 # Container port
#        published: 38001 # Host port exposed on the nodes
#        protocol: tcp
#        mode: host
#    volumes:
#      - redis_ui:/data

# Define the overlay network for Swarm
networks:
  localpaas_net:
    external: true
  internal_net:
    driver: overlay
    attachable: true

volumes:
  db_data:
    driver: local
  redis:
    driver: local
  redis_ui:
    driver: local
