name: '[Dev] Build and Deploy'

on:
  push:
    tags:
      - 'dev-**'

env:
  APP_IMAGE_NAME: localpaas/localpaas-dev
  AGENT_IMAGE_NAME: localpaas/localpaas-agent-dev

jobs:
  build-image:
    strategy:
      matrix:
        include:
          # Intel/AMD builds for App
          - image_name: localpaas/localpaas-dev
            dockerfile: deployment/dev/Dockerfile
            platform: linux/amd64
            runner: ubuntu-24.04
            arch: amd64

          # ARM builds for App
          - image_name: localpaas/localpaas-dev
            dockerfile: deployment/dev/Dockerfile
            platform: linux/arm64
            runner: ubuntu-24.04-arm
            arch: arm64

          # Intel/AMD builds for Agent
          - image_name: localpaas/localpaas-agent-dev
            dockerfile: deployment/dev/Dockerfile.agent
            platform: linux/amd64
            runner: ubuntu-24.04
            arch: amd64

          # ARM builds for Agent
          - image_name: localpaas/localpaas-agent-dev
            dockerfile: deployment/dev/Dockerfile.agent
            platform: linux/arm64
            runner: ubuntu-24.04-arm
            arch: arm64

    # Dynamically select the correct runner machine from the matrix
    runs-on: ${{ matrix.runner }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
          submodules: recursive
      -
        name: Get tag
        run: echo "TAG_VERSION=${GITHUB_REF_NAME#dev-v}" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push natively
        uses: docker/build-push-action@v7
        with:
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          # We can use the 'arch' and 'image_name' directly from our matrix block
          tags: ${{ matrix.image_name }}:${{ github.sha }}-${{ matrix.arch }}

  create-image-manifest:
    needs: build-image
    runs-on: ubuntu-latest # This can run on standard AMD64 since it's just pushing text

    steps:
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create and push multi-arch manifests
        run: |
          TAG_VERSION=${GITHUB_REF_NAME#dev-v}
          
          # App Manifest
          docker buildx imagetools create \
            -t ${{ env.APP_IMAGE_NAME }}:latest \
            -t ${{ env.APP_IMAGE_NAME }}:${TAG_VERSION} \
            ${{ env.APP_IMAGE_NAME }}:${{ github.sha }}-amd64 \
            ${{ env.APP_IMAGE_NAME }}:${{ github.sha }}-arm64
            
          # Agent Manifest
          docker buildx imagetools create \
            -t ${{ env.AGENT_IMAGE_NAME }}:latest \
            -t ${{ env.AGENT_IMAGE_NAME }}:${TAG_VERSION} \
            ${{ env.AGENT_IMAGE_NAME }}:${{ github.sha }}-amd64 \
            ${{ env.AGENT_IMAGE_NAME }}:${{ github.sha }}-arm64

  deploy-app:
    needs: create-image-manifest
    runs-on: ubuntu-latest
    steps:
      - name: Deploy LocalPaaS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEV_SRV_IP }}
          port: ${{ secrets.DEV_SRV_SSH_PORT }}
          username: ${{ secrets.DEV_SRV_USERNAME }}
          password: ${{ secrets.DEV_SRV_PASSWORD }}
          script: curl -sL "https://raw.githubusercontent.com/localpaas/localpaas/main/deployment/dev/install.sh" | bash
